spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lenslink
    username: lenslink
    password: test

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

openai:
  api-key: dummy

naver:
  client-id: dummy
  client-secret: dummy
