spring:
  application:
    name: lenslink

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

openai:
  api-key: ${OPEN_API_KEY}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info